services:
  glances:
    image: nicolargo/glances:latest-full
    container_name: docker-dodge-glances
    restart: unless-stopped
    ports:
      - '9100:61208' # <--- Cambiamos a un puerto alto y seguro
    environment:
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro