version: '3.8'

services:
  photoprism:
    image: photoprism/photoprism:latest
    container_name: euge_photoprism
    ports:
      - "2342:2342"
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "alumnos2026" 
      PHOTOPRISM_AUTH_MODE: "password"
      PHOTOPRISM_SITE_URL: "http://localhost:2342/"
      PHOTOPRISM_STORAGE_PATH: "/photoprism/storage"
    volumes:
      - ./originals:/photoprism/originals
      - ./storage:/photoprism/storage
    restart: unless-stopped