services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    environment:
      - SIGNUPS_ALLOWED=true
      - DOMAIN=http://localhost:8080
      - ADMIN_TOKEN=alumnos2026  
    volumes:
      - ./vw-data:/data
    ports:
      - 8080:80

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '81:81'   # Panel de administración
      - '80:80'   # Tráfico HTTP
      - '443:443' # Tráfico HTTPS
    volumes:
      - ./npm-data:/data
      - ./npm-letsencrypt:/etc/letsencrypt

  tailscale:
    container_name: tailscale-container
    image: tailscale/tailscale:latest
    restart: unless-stopped
    hostname: paloma-docker-node
    environment:
      - TS_STATEFUL_CONFIG=true
    volumes:
      - ./tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE